### ISSUE TITLE
Add Tabler

### ISSUE THREAD

**Issue by alexeygolev** [iconify/iconify-figma#21]
[Tabler Icons](https://tablericons.com/) seems like a good set to have available in the plugin.

Thank you for the plugin!

**Comment by cyberalien** [comment]
Thanks!

That is a really good icon set. Added.

Like in original set, you can change stroke width in Iconify components by targeting `.icon-tabler` in stylesheet:
```css
.icon-tabler {
  stroke-width: 1.25;
}
```
